spring:
  application:
    name: CRM
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: 'postgres'
    password: '2000tzsj'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 'update'

    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

#  mail:
#    host: "imap.gmail.com"
#    username: "your email"
#    password: "your password"
#    port: 993

# App Properties
digitalBox:
  app:
    jwtSecret: '4B6150645367566B59703373367639792442264529482B4D6251655468576D5A'
    jwtExpirationMs: 86400000

profile:
  image:
    upload:
      dir: D:/Projects/CRM Application/CRM BackEnd/src/main/resources/profilePictures

server:
  port: 8082